### ISSUE TITLE
Right-click image "link" copy

### ISSUE THREAD

**Issue by developergunny** [rpearce/image-zoom#298] opened 2022-01-29 02:03 UTC
I need the ability to copy image link with right click. Can it be?

**Comment by rpearce** [comment] 2022-01-29 03:24
Hi and thanks for participating! I know this is an issue, and it's a duplicate of https://github.com/rpearce/image-zoom/issues/259.

When I am able to get back to this project, this will be handled. Until then, there's no way around it.

**Closed by rpearce** 2022-01-29 03:24 UTC

**Comment by developergunny** [comment] 2022-01-29 03:37
Thanks:)

**Comment by rpearce** [comment] 2022-08-03 03:40
This should now be resolved in `5.0.0`
