### ISSUE TITLE
Storybook Example Website Down

### ISSUE THREAD

**Issue by danielbyun** [rpearce/image-zoom#254] opened 2020-07-02 01:43 UTC
Storybook Example site seems to be down?

**Comment by rpearce** [comment] 2020-07-02 12:51
@danielbyun where are you trying to access it from? NPM, GitHub, or somewhere else?

https://rpearce.github.io/image-zoom/

(duplicate of https://github.com/rpearce/image-zoom/issues/253)

**Comment by rpearce** [comment] 2020-07-02 12:52
Also, please be aware that I'm getting very close to https://github.com/rpearce/image-zoom/pull/244, which will be version 5

**Comment by danielbyun** [comment] 2020-07-03 00:34
Ah, the links on the readme and NPM seem to be outdated.

They both point to `https://rpearce.github.io/react-medium-image-zoom/`

**Comment by rpearce** [comment] 2020-07-06 13:17
Okay, thanks. That'll be updated in the near future

**Closed** 2021-03-28 02:36 UTC
